services:

  vision:
    image: vision:latest
    container_name: vision
    build:
      context: services/vision
      additional_contexts:
        common: common
      dockerfile: ../../dockerfiles/Dockerfile.vision
    ports:
      - "9500:8000"

  orchestrator:
    image: orchestrator:latest
    container_name: orchestrator
    build:
      context: services/orchestrator
      additional_contexts:
        common: common
      dockerfile: ../../dockerfiles/Dockerfile.orchestrator
    ports:
      - "9600:8000"
